import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hangman Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[url('/assets/images/background-mobile.svg')] bg-no-repeat bg-cover h-screen md:bg-[url('/assets/images/background-tablet.svg')] lg:bg-[url('/assets/images/background-desktop.svg')]">
        {children}
      </body>
    </html>
  );
}
